sudo: required
language: bash
services:
  - docker
env:
  global:
    - CT_RELEASE=1.0.1
    - BR_RELEASE=2015.08.1-rev1
    - BR_TRAVIS_RELEASE=1.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libncurses5-dev rsync cpio python unzip bc wget
install:
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.install.pre ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.install.pre; fi
  - wget https://raw.githubusercontent.com/saltosystems/buildroot-travis/v${BR_TRAVIS_RELEASE}/.travis.yml.install -O - | bash -e
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.install.post ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.install.post; fi
script:
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.script.pre ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.script.pre; fi
  - wget https://raw.githubusercontent.com/saltosystems/buildroot-travis/v${BR_TRAVIS_RELEASE}/.travis.yml.script -O - | bash -e
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.script.post ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.script.post; fi
after_failure:
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.after_failure.pre ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_failure.pre; fi
  - wget https://raw.githubusercontent.com/saltosystems/buildroot-travis/v${BR_TRAVIS_RELEASE}/.travis.yml.after_failure -O - | bash -e
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.after_failure.post ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_failure.post; fi
after_success:
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.after_success.pre ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_success.pre; fi
  - wget https://raw.githubusercontent.com/saltosystems/buildroot-travis/v${BR_TRAVIS_RELEASE}/.travis.yml.after_success -O - | bash -e
  - if [ -f ${TRAVIS_BUILD_DIR}/.travis.yml.after_success.post ]; then bash -e ${TRAVIS_BUILD_DIR}/.travis.yml.after_success.post; fi
